/**
 * Kill switch for a stale service worker during development.
 *
 * `public/sw.js` is generated by a production build and is still served by
 * `next dev`, so a service worker registered from a previous production run
 * keeps controlling `localhost` and serves the precached production chunks.
 * The dev chunks and the precached ones then get mixed up, which crashes the
 * client bundle and leaves the page stuck on its initial loading state.
 *
 * In development `/sw.js` is rewritten to this handler (see `next.config.ts`),
 * which serves a service worker that drops every cache and unregisters itself.
 */
const KILL_SWITCH_WORKER = `self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.map((key) => caches.delete(key)));
    await self.registration.unregister();
    const clients = await self.clients.matchAll({ type: 'window' });
    for (const client of clients) {
      try {
        await client.navigate(client.url);
      } catch {
        // the client may already be gone; nothing to reload then
      }
    }
  })());
});
`;

export function GET() {
  if (process.env.NODE_ENV !== "development")
    return new Response(null, { status: 404 });
  return new Response(KILL_SWITCH_WORKER, {
    headers: {
      "content-type": "text/javascript; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}
